# Generated by Django 3.2.6 on 2021-08-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=30)),
                ('director_surname', models.CharField(max_length=30)),
                ('director_age', models.IntegerField()),
            ],
        ),
    ]
