# Generated by Django 3.2.4 on 2021-08-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('dirco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_director.director')),
            ],
        ),
    ]
